import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
          crossorigin="anonymous"
        ></script>

        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
          integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
          integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
          crossorigin="anonymous"
        ></script>
      </Head>

      <main>
        <div
          className="container-fluid bg-light"
          style={{ backgroundColor: "#FFFFFF" }}
        >
          <header style={{ backgroundColor: "#F7F9FF" }}>
            <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>
              <nav
                className="navbar bg-body-tertiary"
                style={{ backgroundColor: "#F7F9FF" }}
              >
                <div className="container-fluid">
                  <a className="navbar-brand" href="#">
                    <img
                      src="/designerr-logo.png"
                      alt="Logo"
                      width="72%"
                      height="auto"
                      class="d-inline-block align-text-top"
                    />
                  </a>
                </div>
              </nav>
            </div>
          </header>
          <div
            className="body-content d-flex justify-content-center mt-5 bg-light"
            style={{ backgroundColor: "#FFF" }}
          >
            <div
              className="card shadow p-3 mb-5 bg-body-tertiary rounded"
              style={{ maxWidth: 730, backgroundColor: "#FFF" }}
            >
              <div className="card-body">
                <h5 className="card-title text-center text-uppercase fw-bold">
                  Sign Up
                </h5>

                <div className="mb-3">
                  <label
                    for="exampleFormControlInput1"
                    className="form-label fw-bold"
                  >
                    Name *
                  </label>
                  <input
                    type="name"
                    className="form-control p-3"
                    id="exampleFormControlInput1"
                    placeholder="Enter your username"
                    width="100%"
                    height="85%"
                  />
                </div>

                <div className="mb-3">
                  <label
                    for="exampleFormControlInput1"
                    className="form-label fw-bold"
                  >
                    Email *
                  </label>
                  <input
                    type="email"
                    className="form-control p-3"
                    id="exampleFormControlInput1"
                    placeholder="Enter your email address"
                    width="100%"
                  />
                </div>

                <div className="mb-3">
                  <label
                    for="exampleFormControlInput1"
                    className="form-label fw-bold"
                  >
                    Password *
                  </label>
                  <input
                    type="password"
                    className="form-control p-3"
                    id="exampleFormControlInput1"
                    placeholder="Create a password"
                    width="100%"
                  />
                </div>
                <div className="mb-4">
                  <div className="row d-flex p-2 ">
                    <button
                      type="button"
                      className="btn btn-primary text-uppercase"
                      width="100%"
                    >
                      Sign in with Email
                    </button>
                  </div>
                </div>

                <div className="mb-2">
                  <div className="row d-flex  p-2">
                    <button
                      type="button"
                      className="btn btn-outline-dark "
                      width="100%"
                    >
                      <span>
                        <img
                          className="img-thumbnail bg-transparent border-0"
                          src="/Google logo.svg"
                        ></img>
                      </span>
                      Sign in with Google
                    </button>
                  </div>
                </div>

                <div className="mb-3">
                  <div className="row d-flex p-2 ">
                    <button
                      type="button"
                      className="btn btn-outline-dark "
                      width="100%"
                    >
                      <span>
                        <img
                          className="img-thumbnail bg-transparent border-0"
                          src="/fb-logo.svg"
                        ></img>
                      </span>
                      Sign in with Facebook
                    </button>
                  </div>
                </div>

                <div className="mb-3">
                  <p className="text-center">
                    By continuing your agree to our privacy policy and terms and
                    conditions.
                  </p>
                </div>

                <div className="mb-3">
                  <p className="text-center">
                    Already have an account?
                    <span>
                      <a className="text-primary" href="#">
                        {" "}
                        Sign in
                      </a>
                    </span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
