import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";
// import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
// import { faSearch } from "@fortawesome/free-solid-svg-icons";
// import Image from 'next/image';
// import { faAngleRight } from "@fortawesome/free-solid-svg-icons";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
          crossorigin="anonymous"
        ></script>

        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
          integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
          integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
          crossorigin="anonymous"
        ></script>
      </Head>

      <div
        className="container-fluid bg-light"
        style={{ backgroundColor: "#FFFFFF" }}
      >
        <header style={{ backgroundColor: "#F7F9FF" }}>
          <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <div className="container-fluid">
                <a className="navbar-brand" href="#">
                  <img
                    src="/designerr-logo.png"
                    alt="Logo"
                    width="72%"
                    height="auto"
                    class="d-inline-block align-text-top"
                  />
                </a>

                <div
                  className="collapse navbar-collapse d-flex justify-content-end"
                  id="navbarSupportedContent"
                >
                  <div className="d-flex justify-content-end">
                    <img
                      src="/user-img1.png"
                      alt="Logo"
                      width="72%"
                      height="auto"
                      class="d-inline-block align-text-top"
                    />
                    <p style={{ fontSize: 16 }}>John Doe</p>
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </header>

        <div className="row">
          <div className="container max814-2">
            <div className="row">
              <div
                className="col-3"
                style={{
                  backgroundColor: "#fff",
                  color: "#000",
                  height: "850px",
                }}
              >
                <div style={{ backgroundColor: "transparent" }}>
                  <div class="m-3">
                    <button class="new-chat" id="sidebarNewChat_btn">
                      + New Chat
                    </button>
                  </div>

                  {/* today */}
                  <div className="mt-4">
                    <p className="tyni-heading1 mx-3 ">Today</p>
                    <ul className="text-start">
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                    </ul>
                  </div>
                  {/* Yesterday */}
                  <div className="mt-4">
                    <p className="tyni-heading1 mx-3 ">Yesterday</p>
                    <ul className="text-start">
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                    </ul>
                  </div>
                  {/* Previous 7 Days */}
                  <div className="mt-4">
                    <p className="tyni-heading1 mx-3 ">Previous 7 Days</p>
                    <ul className="text-start">
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div
                className="col-9"
                style={{ backgroundColor: "#F2F5FF", color: "#000" }}
              >
                <div>
                  <p
                    className="m-0 p-4 "
                    style={{ backgroundColor: "#fff", color: "#000" }}
                  >
                    User: Create a Landing page about Backend Engineering with
                    this website references www.designer.com
                  </p>
                </div>

                <div>
                  <p className="p-4">
                    AI: Noted on that... Please wait in a bit, Thanks!
                  </p>
                </div>

                <div>
                  <p className="p-4">
                    AI: Thank you for waiting! Kindly see the results below:{" "}
                  </p>

                  <Image
                    src="/../public/Frame 1000003921.png"
                    className="p-2"
                    width={400}
                    height={450}
                    alt="Picture 2"
                    id="sidebar-right-img"
                  />
                </div>

                {/* bottom-input-field */}

                <div className="row justify-content-md-center">
                  <div className="col-md-auto">
                    {" "}
                    <input
                      type="text"
                      id="searchInput"
                      placeholder="Enter your search query..."
                      width="100%"
                    />
                  </div>
                  <div className="col col-lg-4">
                    {" "}
                    <button onclick="search()">Search</button>
                  </div>
                </div>

                <div className="position-relative">
                  <input
                    type="text"
                    className="form-control lh-lg ps-5"
                    placeholder="Enter the name of a form (e.g., “Oregon Lease Agreement”)"
                  />
                  {/* <FontAwesomeIcon
                    icon={faSearch}
                    className="position-absolute search_icon"
                  /> */}
                </div>
                <button type="button" className="btn btn-success my-5 home_btn">
                  <span>
                    <Image
                      src="/images/icons/Comment.png"
                      alt="My Image"
                      width={16}
                      height={10}
                      className="me-2"
                    />
                    Begin
                  </span>
                </button>
              </div>
            </div>

            {/*------------------------------------------------  */}

            {/* <div className="row ">
              <div
                className="col-9 pt-5"
                style={{ backgroundColor: "#494659" }}
                id="bottom-right-side"
              >
                <div
                  style={{ backgroundColor: "#A4AAB6" }}
                  id="input-container"
                >
                  <div
                    className="input-group mb-3 bg-transparent"
                    class="input-wrapper"
                  >
                    <input
                      type="text"
                      id="user-input"
                      placeholder="Type your message..."
                    />

                    <button id="send-button">
                      <span
                        className="input-group-text bg-transparent"
                        id="basic-addon2"
                      >
                        <Image
                          src="/images/icons/Frame 1000003894.png"
                          alt="My Image"
                          width={16}
                          height={10}
                          className="me-2 cment_nofill"
                        />
                      </span>
                    </button>
                  </div>
                </div>
              </div>
            </div> */}
          </div>
        </div>
      </div>
    </div>
  );
}
