import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";

export default function Signup() {
  return (
    <div>
      <Head>
        <title>Designerr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
          crossorigin="anonymous"
        ></script>

        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
          integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
          integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
          crossorigin="anonymous"
        ></script>
      </Head>

      <main>
        <div className="container" style={{ backgroundColor: "#F7F9FF" }}>
          <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>
            <nav className="navbar bg-body-tertiary">
              <div className="container-fluid">
                <a className="navbar-brand" href="#">
                  <img
                    src="/designerr-logo.png"
                    alt="Logo"
                    width="72%"
                    height="auto"
                    class="d-inline-block align-text-top"
                  />
                </a>
              </div>
            </nav>
          </div>

          <div className="body-content d-flex justify-content-center mt-6 ">
            <div className="row">
              <div className="col-3 mt-5">
                <h1>Create YOUR DESIGNS</h1>
                <br />
                <button type="button" class="btn btn-primary btn-lg">
                  EDIT
                </button>
              </div>
              <div className="col-3">
                <Image
                  src="/Frame1.png"
                  width={400}
                  height={450}
                  alt="Picture 1"
                />
              </div>
              <div className="col-3">
                <Image
                  src="/Frame2.png"
                  width={400}
                  height={450}
                  alt="Picture 2"
                />
              </div>

              <div className="col-3">
                <Image
                  src="/Frame3.png"
                  width={400}
                  height={450}
                  alt="Picture 3"
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
