import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";

export default function Payment() {
  return (
    <div>
      <Head>
        <title>Designerr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
          crossorigin="anonymous"
        ></script>

        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
          integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
          integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
          crossorigin="anonymous"
        ></script>
      </Head>

      <main>
        <div className="container-fluid" style={{ backgroundColor: "#F7F9FF" }}>
          <header>
            <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>
              <nav className="navbar bg-body-tertiary">
                <div className="container-fluid">
                  <a className="navbar-brand" href="#">
                    <img
                      src="/designerr-logo.png"
                      alt="Logo"
                      width="72%"
                      height="auto"
                      class="d-inline-block align-text-top"
                    />
                  </a>
                </div>
              </nav>
            </div>
          </header>
          <div className="row">
            <h1 className="text-center text-primary text-uppercase">
              Enter Your Payment Details Below
            </h1>
          </div>

          <div className="body-content d-flex justify-content-center mt-6 ">
            <div className="row">
              <div className="col-12 col-md-7 col-lg-7">
                <div className="card shadow p-3 mb-5 bg-body-tertiary rounded">
                  <div className="card-body">
                    <h5 className="card-title text-left">
                      Payment Information
                    </h5>

                    <div className="mb-3">
                      <label
                        for="exampleFormControlInput1"
                        className="form-label"
                      >
                        Name *
                      </label>
                      <input
                        type="email"
                        className="form-control"
                        id="exampleFormControlInput1"
                        placeholder="Enter your username"
                      />
                    </div>

                    <div className="mb-3">
                      <label
                        for="exampleFormControlInput1"
                        className="form-label"
                      >
                        Email address *
                      </label>
                      <input
                        type="email"
                        className="form-control"
                        id="exampleFormControlInput1"
                        placeholder="Enter your email address"
                      />
                    </div>

                    <div className="mb-3">
                      <label
                        for="exampleFormControlInput1"
                        className="form-label"
                      >
                        Card Details *
                      </label>
                      <input
                        type="number"
                        className="form-control"
                        id="exampleFormControlInput1"
                        placeholder="0000 0000 0000 0000"
                      />
                    </div>
                    <div className="mb-3">
                      <div className="row d-flex  ">
                        <button
                          type="button"
                          className="btn btn-primary "
                          width="200%"
                        >
                          submit
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-12 col-md-5 col-lg-5">
                <div className="card  shadow bg-body-tertiary rounded">
                  <div className="card-body">
                    <p className="card-subtitle  text-left text-primary">
                      You have to pay
                    </p>
                    <h1 className="card-title text-left  mb-2 text-muted">
                      $99/mo
                    </h1>
                    <hr></hr>
                    <h6 className="card-text text-left ">What’s included</h6>

                    <ul>
                      <li>Eget nunc scelerisque viverra</li>
                      <li>Mauris in aliquam</li>
                      <li>Nunc faucibus a pellentesque sit</li>
                      <li>Ut sem viverra aliquet</li>
                      <li>Pretium vulputate sapien</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
